condensed scripts down, formatted, etc..

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,11 +1,12 @@
-#!/bin/bash
 
-set -euo pipefail
+# Exit immediately if a command exits with a non-zero status
+set -eEo pipefail
 
 export CHRONOS_PATH="${CHRONOS_PATH:-$HOME/.local/share/chronos}"
 
 source "$CHRONOS_PATH/lib/functions.sh"
 
+source "$CHRONOS_PATH/scripts/00-prerequisites/check-requirements.sh"
 source "$CHRONOS_PATH/scripts/00-prerequisites/gum-install.sh"
 source "$CHRONOS_PATH/scripts/00-prerequisites/set-variables.sh"
 source "$CHRONOS_PATH/scripts/00-prerequisites/yay-install.sh"
